language: python
python:
  - "3.6"

env:
  global:
    # Docker username and password
    - secure: "k+IwHSSBwJlgH1BwJtL+lzm8ZftZIewOOgnPor+ydXTfwnK6a9D04C+FifrQWApOqB7nYSdYTarKz/1rh/dNy8OIW62AOG3G4wfdCVORB+G3PENxlXaqoEpm1Qap8KRHL3tSLZmlzoE1VnLe6r4sYNkn0JcQdDKeyI1hJWQd4x4RqaiGZXjP+RpCoLGfiQVJNY9HqvSPhBMMNt/NOss2+Rk/QgPMcMv4dCBWppZUk5SRC2GVDyqCA4HqdRv1D8FBVXem2PepSJ2hX0P4gJjqtiCBHwGB8opSIaAkTqH0vayxxfz6r+KHw8NLz2BaKyW4EcSjDsOWUlZBpHysMvRT2/Vf0KzYSoQoJjQIbHxX1hQQ39gIoB2ngaFpWi07WcCLLRrWiQA/0qopiM2iDAYq2Bw8pzVENahZl7ewW1woZeBuO/O/wkHkvEAqO+1QKZ0BILGQS/mN/QZclXlDK6BpUGpTujrNta4+O2ZOBm3AdGycgx8Hqjj82CaquLNgGeOM6GjZN3p2kZ2MB0KDYVv1FcvGTpCvfHsHvWPblVrUG3P3MjlEM4TUVH9G8foV9v3Ek1QXJTNbePcJyK1fodnjpp5c9uwN2zMylDMgoIzlnyoyvV8PdERjpE2oTuebuHh0eX0NyXBTx9UyYf43ON29kmYj/G60HNbvaLUpKhjlWnQ="
    - secure: "MzH58n1jDaCvA24jJ6zm1KJZfNNB5LwvZj1G/oPlpyj7OrC2eq02QEkf+nd0fk0cdhnR21fwjgKwbJZq9TPpZed7PQpuxxzu0tGVr6dEQmxk90lRr7ZYSfNqit7pmj+HgUy3ECzt1oLVsce7iWlJKPhdRSzcFggUoeHWcSarXni7OW9TIS/exFtpZ+f5/yAIx/quCnl7UTolODnR7VxSpr+UsBDWUCSQpLWxufWPvfSfCu9POx2HWOoIsoF9ovwsCK4zxdR21kvTPgBjfKnDnNoO7LudmGynlgq4sX5UDeIpJbX+FMCfTo3DprXt5tXWslWFuxgNFsEvydaribf4O/i+V21DODg3vTv4EtCRm+3yeSUoCNz2CPn4JxudJGDBX3E7fyeau9sU8CINqCEWC83oYgXgNUEjZj9Q1747bvji1iD/sRUwRSZDPAr7wY6QwrckXPnrnDIr3sQyylwk73W3zmuQC6xyWU2P3UO0MOQp3QRl+ft3MDTZ842CFkbKrg5UKHE1RiS8vu+rtpNR4Xv7p4hLN1dtvY/S8H8q727lCHYv3RL25OU0arLJ/hhV6DP6klBnpMJQCLXqXoxP2ngZWw6Am9sgJlQG1NNrLv9Mbk6SldYvpK/DEZjH1MgMhF5Cmgjzej49r7neVpUrFmarWmRkImSxhXqEMU+vCjQ="

sudo: required
services:
  - docker

addons:
  apt:
    packages:
    - libleveldb-dev
    - libsqlite3-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - coverage run -m unittest discover neo
  - coverage run -m -a unittest discover boa_test
  - pycodestyle prompt.py
  - pycodestyle api_server.py
  - pycodestyle neo
  - pycodestyle examples
  - python prompt.py --version

after_success:
    coveralls

deploy:
  # Deploy to PyPI
  - provider: pypi
    user: CityOfZion
    password:
      secure: NVvbRCt5JwHE6MhQjj0O0Lui/USEr/fnTHdYRKfPi75p+7rqVPJ47uE0fx/3GCZf1cp+fHQB0oTm+NU+asqAlIJ6HOq3HwwbDFtwvzBiIPc9eq14jqAhplRF4rV8nYHm1HcvJuJyfre+3qqFlu86x9/j5RdWC6RrNpbFnqyrYkpK1vWZwZFeMgdxJ4yCd8u8Cuh+uFjF80BWKSOLXrPLcJHKkrprN8GJRxt+dh6LAfdsQ1mHnn2JqT4FDiR6cLHZKLC+b5F61rjk1OYdw9hnA/XZtCz2qEQn4Sct+jSLxNmcX+hGqvTH86N2gEjRasU11Slu/bDgyUQkELyWjnHpRsNYTvZyT3ilG7mrmN2JIxUcPaVQ3SgTqsPBeE058OCTHA0zvkNkR5838wfIfeSv5Q+Obn3wsceK4m2LOrlRElxRckjIcQtDzoOihEV5yU3Kqym6yX67AsB1m2JsBRZMCztsf29RgtsLLXzID76rAuc1KmLq6jL5Uo7RieoeSKY2Gy/TLwh6+g/hC8P6L8Sq7NJCvd1+keRiWYQw7bq3MKVBBnI59riZaz82s+a/qYo72UMTfb+VLZ1Dv+V1Bllj2chILWGuCd/tylF+tIGaA4Z70govsJ4Arsz0u37fL+4Qx98sWWAtS9JRv+X8XhR4xtAKzKBGihJ5Tc42y+6z5yM=
    distributions: sdist bdist_wheel
    on:
      tags: true
      repo: CityOfZion/neo-python

  # Deploy to Docker Hub
  #- provider: script
  #  script: bash docker/travis-deploy-to-docker-hub.sh
  #  on:
  #    tags: true
