language: python
python:
  - "3.6"

addons:
  apt:
    packages:
    - libleveldb-dev
    - libsqlite3-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - coverage run -m unittest discover neo
  - coverage run -m -a unittest discover boa_test
  - pycodestyle prompt.py
  - pycodestyle api-server.py
  - pycodestyle neo
  - pycodestyle examples
  - python prompt.py --version

after_success:
    coveralls

deploy:
  true:
    tags: true
    python: 3.6
    repo: CityOfZion/neo-python
  distributions: sdist bdist_wheel
  password:
    secure: QZ3rkZQ6GAGAb52cyU5yG10ILSUwDEIrpCMkj16OaMQ1Gkl2AMWf2SAlLT29j8irVWkPx2Adj49g096wBdbi1SMlFdLHZxorGQYFnV30DrbLNW2Fv1wegzHRq8nMj1drSc19/t9yhb1TcUYsI/eaSZ9JpBf3fjsrBEnS32P2Q5I5OSh35VEA0emo46KyOIhY0+Ajy5OLAN632IQOy6LmkAeIjDfivdEwtfPCEKhqSbh9LbHm5sgh0XzDwqte+2mMrBPVMwuV0PuTFkTzlioXfVsKvVLjD0e1dFiZZUI4ABdKEW0jrhijCP+REOc2O6Wsi0eilVnWYI74AWlX7M2jdm1B43Mu6ZT3VQVMzQ/3zLytp6jiffiFiirMoSNosrjJvl/YZDVqBBETi8jOfZKL2iIqwVt5JGcNHNQMTVSIxEFWJWhAnq/5VdJMSB6w6fXlZFnRlpEAJk0AYhQUYPyyqbU7XPrrAFRevMOEc6q9TRkjZLdzrD2Tt0kIpV8H2IOudWNxc3rpkVYSJ8sLPFwLOtzkwtffUSagFj3gjp7XInt9k09UhFRkU4xAsLb9fV+PBKx+rsRtYF4GiZHXEB3f/BuM+rden2Lrb7uqoTKSyF0Wy1kLLEsevvllTuQvV/EIF1cTzrGLIFAFtWCERStlvIDMHHwGlJW/+oJ8KXX2Pto=
  provider: pypi
  user: CityOfZion

