language: python
python:
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - libleveldb-dev


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script: coverage run -m unittest discover neo


after_success:
    coveralls