language: python
python:
  - "3.5"

addons:
  apt:
    packages:
    - libleveldb-dev


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script: ./test.sh


after_success:
    coveralls